# ForesightX DVC Pipeline
# ========================
# Data Version Control pipeline for stock market prediction
# Tracks data, models, and reproducible ML workflows

stages:
  # Stage 1: Data Ingestion
  # Fetch historical stock data from Yahoo Finance
  data_ingestion:
    cmd: python src/data/make_dataset.py
    deps:
      - src/data/make_dataset.py
      - src/services/logger.py
    params:
      - data_ingestion.stock_symbol
      - data_ingestion.start_date
      - data_ingestion.end_date
      - data_ingestion.source
    outs:
      - data/raw/stock_data_raw_${data_ingestion.stock_symbol}.csv

  # Stage 2: Data Preprocessing
  # Clean, validate and split data
  data_preprocessing:
    cmd: python src/data/preprocess.py
    deps:
      - src/data/preprocess.py
      - data/raw/stock_data_raw_${data_ingestion.stock_symbol}.csv
    params:
      - data_ingestion.stock_symbol
      - preprocessing.handle_missing
      - preprocessing.remove_outliers
      - preprocessing.outlier_method
      - preprocessing.outlier_threshold
    outs:
      - data/processed/train_data_${data_ingestion.stock_symbol}.csv
      - data/processed/test_data_${data_ingestion.stock_symbol}.csv

  # Stage 3: Feature Engineering
  # Create 113 technical indicators and features
  feature_engineering:
    cmd: python src/features/build_features.py
    deps:
      - src/features/build_features.py
      - data/processed/train_data_${data_ingestion.stock_symbol}.csv
      - data/processed/test_data_${data_ingestion.stock_symbol}.csv
    params:
      - data_ingestion.stock_symbol
      - feature_engineering.lag_periods
      - feature_engineering.sma_windows
      - feature_engineering.ema_windows
      - feature_engineering.rsi_windows
      - feature_engineering.macd_fast
      - feature_engineering.macd_slow
      - feature_engineering.macd_signal
      - feature_engineering.bollinger_window
      - feature_engineering.bollinger_std
      - feature_engineering.atr_windows
      - feature_engineering.volatility_windows
      - feature_engineering.volume_ma_windows
      - feature_engineering.vwap_window
      - feature_engineering.roc_periods
      - feature_engineering.target_return_window
    outs:
      - data/features

  # Stage 4: Model Training
  # Train MLP model with validation
  train_model:
    cmd: python src/model/train_model.py
    deps:
      - src/model/train_model.py
      - data/features
    params:
      - data_ingestion.stock_symbol
      - training.test_size
      - training.validation_size
      - training.random_state
      - training.early_stopping_patience
      - models.mlp.hidden_layer_sizes
      - models.mlp.activation
      - models.mlp.solver
      - models.mlp.learning_rate_init
      - models.mlp.max_iter
      - models.mlp.early_stopping
    outs:
      - models

  # Stage 5: Model Evaluation
  # Evaluate model on test set with MLflow tracking
  evaluate_model:
    cmd: python src/model/evaluate_model.py
    deps:
      - src/model/evaluate_model.py
      - models
      - data/features
    params:
      - data_ingestion.stock_symbol
      - training.test_size
      - evaluation.metrics
      - mlflow.enabled
      - mlflow.experiment_name
    outs:
      - results

  # Stage 6: Model Registry
  # Register model in MLflow Model Registry
  register_model:
    cmd: python src/model/model_registry.py
    deps:
      - src/model/model_registry.py
      - models
      - metadata
    params:
      - data_ingestion.stock_symbol
      - mlflow.enabled
      - mlflow.dagshub_username
      - mlflow.dagshub_repo
      - model_registry.default_stage

# Remote storage configuration (optional)
# Uncomment and configure for S3 or other cloud storage
# remote:
#   myremote:
#     url: s3://foresightx-models
#     region: us-east-1